### ISSUE TITLE
After Installing the IBM Cloud CLI it is automatically picking up the git file location

### ISSUE THREAD

**Issue by shubh802** [IBM/ibm-cloud-functions-refarch-serverless-image-recognition#22]
After Installing the IBM Cloud CLI it is automatically picking up the git file location.
So when i try to run the login command it is showing as failed as it picking up the path of the git file by default. In this is case git config location is a shared drive which is not accessible at that time.
ibmcloud login -a cloud.ibm.com -o "**********@gmail.com" -s "dev"
FAILED
Configuration error: open H:\.bluemix\plugins\config.json: The system cannot find the path specified.
Expected: There should be a way we can configure the git config file location. It should not pick it up automatically or a way to change it later.

**Comment by AnthonyAmanse** [comment]
@shubh802 this seems like a problem with the `ibmcloud` cli installation. You can change the ibmcloud config directory by setting the environment variable `IBMCLOUD_HOME=path/to/dir`.

Or it looks like `H:` is set as your home drive. I don't have experience with windows but try doing this one from: https://stackoverflow.com/a/52833743
```
C:\Users\MyUser> $env:HOMEDRIVE="c:"
C:\Users\MyUser> $env:HOMEPATH="\Users\MyUser"
```
> `c:` or whatever drive letter you're using
